{{- if .Values.imageCredentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
  labels:
    app: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}